In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("ParisHousing for Linear Regression.csv")

In [3]:
df.head()

,squareMeters,numberOfRooms,hasYard,hasPool,floors,cityCode,cityPartRange,numPrevOwners,made,isNewBuilt,hasStormProtector,basement,attic,garage,hasStorageRoom,hasGuestRoom,price
0,75523,3,0,1,63,9373,3,8,2005,0,1,4313,9005,956,0,7,7559081.5
1,80771,39,1,1,98,39381,8,6,2015,1,0,3653,2436,128,1,2,8085989.5
2,55712,58,0,1,19,34457,6,8,2021,0,0,2937,8852,135,1,9,5574642.1
3,32316,47,0,0,6,27939,10,4,2012,0,1,659,7141,359,0,3,3232561.2
4,70429,19,1,1,90,38045,3,7,1990,1,0,8435,2429,292,1,4,7055052.0

squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
squareMeters,10000.0,4.987013e+04,2.877438e+04,89.0,25098.50,50105.5,74609.75,99999.0
numberOfRooms,10000.0,5.035840e+01,2.881670e+01,1.0,25.00,50.0,75.00,100.0
hasYard,10000.0,5.087000e-01,4.999493e-01,0.0,0.00,1.0,1.00,1.0
hasPool,10000.0,4.968000e-01,5.000148e-01,0.0,0.00,0.0,1.00,1.0
floors,10000.0,5.027630e+01,2.888917e+01,1.0,25.00,50.0,76.00,100.0
cityCode,10000.0,5.022549e+04,2.900668e+04,3.0,24693.75,50693.0,75683.25,99953.0
cityPartRange,10000.0,5.510100e+00,2.872024e+00,1.0,3.00,5.0,8.00,10.0
numPrevOwners,10000.0,5.521700e+00,2.856667e+00,1.0,3.00,5.0,8.00,10.0
made,10000.0,2.005488e+03,9.308090e+00,1990.0,1997.00,2005.5,2014.00,2021.0
isNewBuilt,10000.0,4.991000e-01,5.000242e-01,0.0,0.00,0.0,1.00,1.0
hasStormProtector,10000.0,4.999000e-01,5.000250e-01,0.0,0.00,0.0,1.00,1.0
basement,10000.0,5.033104e+03,2.876730e+03,0.0,2559.75,5092.5,7511.25,10000.0
attic,10000.0,5.028011e+03,2.894332e+03,1.0,2512.00,5045.0,7540.50,10000.0
garage,10000.0,5.531212e+02,2.620502e+02,100.0,327.75,554.0,777.25,1000.0
hasStorageRoom,10000.0,5.030000e-01,5.000160e-01,0.0,0.00,1.0,1.00,1.0
hasGuestRoom,10000.0,4.994600e+00,3.176410e+00,0.0,2.00,5.0,8.00,10.0
price,10000.0,4.993448e+06,2.877424e+06,10313.5,2516401.95,5016180.3,7469092.45,10006771.2

In [6]:
x = df[['squareMeters','floors','cityCode']]
x.head()

   squareMeters  floors  cityCode
0         75523      63      9373
1         80771      98     39381
2         55712      19     34457
3         32316       6     27939
4         70429      90     38045

In [7]:
y = df['price']
y.head()

0    7559081.5
1    8085989.5
2    5574642.1
3    3232561.2
4    7055052.0
Name: price, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=5)

In [9]:
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(8000, 3) (2000, 3)
(8000,) (2000,)

In [10]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()

In [11]:
lr_model.fit(x_train, y_train)

LinearRegression()

In [12]:
lr_model.intercept_

np.float64(3757.6327175199986)

In [13]:
lr_model.coef_

array([ 9.99997362e+01,  5.45953039e+01, -8.67592235e-04])

In [14]:
y_pred = lr_model.predict(x_test)
y_pred

array([9748220.88183481, 3355591.05891792,  728397.46536689, ...,
       6015363.69067842, 5801551.34836411, 9344990.73764798],
      shape=(2000,))

In [15]:
len(y_pred)

2000

In [16]:
x_test.head()

      squareMeters  floors  cityCode
7054         97406      72     48318
442          33469      91     29874
3954          7199      87      9290
2288         97392      83     29178
3196         26592      49     43397

In [17]:
df.loc[400]

squareMeters           19014.0
numberOfRooms             67.0
hasYard                    1.0
hasPool                    0.0
floors                    89.0
cityCode               82387.0
cityPartRange              8.0
numPrevOwners              2.0
made                    1999.0
isNewBuilt                 0.0
hasStormProtector          0.0
basement                3330.0
attic                   8941.0
garage                   550.0
hasStorageRoom             0.0
hasGuestRoom               6.0
price                1912984.9
Name: 400, dtype: float64

In [18]:
np.mean(abs(y_test - y_pred)) # MAE

np.float64(2348.7692391392047)

In [19]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [20]:
def model_eve(model_name, y_test, y_pred):
    print(f'{model_name} R2_score', r2_score(y_test, y_pred))
    print(f'{model_name}, MAE ',mean_absolute_error(y_test, y_pred))
    print(f'{model_name}, MSE ',mean_squared_error(y_test, y_pred))
    print(f'{model_name}, RMSE ',root_mean_squared_error(y_test, y_pred))

In [21]:
model_eve('lr_model', y_test, y_pred)

lr_model R2_score 0.9999990273885975
lr_model, MAE  2348.7692391392047
lr_model, MSE  8290748.013491277
lr_model, RMSE  2879.3659047594624

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.05, random_state=4)

from sklearn.linear_model import LinearRegression
best_model = LinearRegression()


# Training of model
best_model.fit(x_train, y_train)

LinearRegression()

In [23]:
best_y_pred = best_model.predict(x_test)
len(best_y_pred)

500

In [24]:
df.iloc[10,0:-1]

squareMeters         23563.0
numberOfRooms           21.0
hasYard                  0.0
hasPool                  1.0
floors                  90.0
cityCode             91058.0
cityPartRange            6.0
numPrevOwners            8.0
made                  1993.0
isNewBuilt               1.0
hasStormProtector        0.0
basement               703.0
attic                  852.0
garage                 684.0
hasStorageRoom           1.0
hasGuestRoom            10.0
Name: 10, dtype: float64

In [25]:
df.iloc[2000]

squareMeters           77747.0
numberOfRooms             50.0
hasYard                    1.0
hasPool                    1.0
floors                    72.0
cityCode               98938.0
cityPartRange              8.0
numPrevOwners             10.0
made                    2014.0
isNewBuilt                 0.0
hasStormProtector          1.0
basement                4829.0
attic                   4204.0
garage                   455.0
hasStorageRoom             0.0
hasGuestRoom               3.0
price                7786197.4
Name: 2000, dtype: float64